# -*- coding: utf-8 -*-
"""QR CODE GENERATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-dhnLWEzyvwu4n3GofUj6hfXH8aK5-ez
"""



import qrcode
from PIL import Image
from IPython.display import display

data = input("Enter text or URL: ")
qr = qrcode.make(data)
display(qr)
qr.save("qr_code.png")

!pip install qrcode

